
package com.inspur.gs.RbAccMsg.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS_ESB_StandardPortType", targetNamespace = "http://www.apusic.com/esb/WS_ESB_Standard")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSESBStandardPortType {


    /**
     * 
     * @param outHead
     * @param reqHead
     * @param reqBody
     * @param outBody
     */
    @WebMethod(action = "http://www.apusic.com/esb/WS_ESB_Standard/sendData")
    @RequestWrapper(localName = "sendData", targetNamespace = "http://www.apusic.com/esb/WS_ESB_Standard", className = "com.spring.webService.ws.SendData")
    @ResponseWrapper(localName = "sendDataResponse", targetNamespace = "http://www.apusic.com/esb/WS_ESB_Standard", className = "com.spring.webService.ws.SendDataResponse")
    public void sendData(
        @WebParam(name = "reqHead", targetNamespace = "http://www.apusic.com/esb/WS_ESB_Standard")
        String reqHead,
        @WebParam(name = "reqBody", targetNamespace = "http://www.apusic.com/esb/WS_ESB_Standard")
        String reqBody,
        @WebParam(name = "outHead", targetNamespace = "http://www.apusic.com/esb/WS_ESB_Standard", mode = WebParam.Mode.OUT)
        Holder<String> outHead,
        @WebParam(name = "outBody", targetNamespace = "http://www.apusic.com/esb/WS_ESB_Standard", mode = WebParam.Mode.OUT)
        Holder<String> outBody);

}
