
package com.inspur.gs.RbAccMsg.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_ESB_Standard", targetNamespace = "http://www.apusic.com/esb/WS_ESB_Standard", wsdlLocation = "http://192.168.0.144:5888/services/WS_ESB_Standard?wsdl")
public class WSESBStandard
    extends Service
{

    private final static URL WSESBSTANDARD_WSDL_LOCATION;
    private final static WebServiceException WSESBSTANDARD_EXCEPTION;
    private final static QName WSESBSTANDARD_QNAME = new QName("http://www.apusic.com/esb/WS_ESB_Standard", "WS_ESB_Standard");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.144:5888/services/WS_ESB_Standard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSESBSTANDARD_WSDL_LOCATION = url;
        WSESBSTANDARD_EXCEPTION = e;
    }

    public WSESBStandard() {
        super(__getWsdlLocation(), WSESBSTANDARD_QNAME);
    }

    public WSESBStandard(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSESBSTANDARD_QNAME, features);
    }

    public WSESBStandard(URL wsdlLocation) {
        super(wsdlLocation, WSESBSTANDARD_QNAME);
    }

    public WSESBStandard(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSESBSTANDARD_QNAME, features);
    }

    public WSESBStandard(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSESBStandard(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSESBStandardPortType
     */
    @WebEndpoint(name = "WS_ESB_StandardHttpSoap11Endpoint")
    public WSESBStandardPortType getWSESBStandardHttpSoap11Endpoint() {
        return super.getPort(new QName("http://www.apusic.com/esb/WS_ESB_Standard", "WS_ESB_StandardHttpSoap11Endpoint"), WSESBStandardPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSESBStandardPortType
     */
    @WebEndpoint(name = "WS_ESB_StandardHttpSoap11Endpoint")
    public WSESBStandardPortType getWSESBStandardHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.apusic.com/esb/WS_ESB_Standard", "WS_ESB_StandardHttpSoap11Endpoint"), WSESBStandardPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSESBSTANDARD_EXCEPTION!= null) {
            throw WSESBSTANDARD_EXCEPTION;
        }
        return WSESBSTANDARD_WSDL_LOCATION;
    }

}
